# Generated by Django 5.0.4 on 2024-04-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry_2',
        ),
    ]
